[pytest]
#addopts = -v --tb=short
addopts = -v --tb=short --alluredir=allure-results --clean-alluredir

#addopts = --alluredir=temps --clean-alluredir --driver chrome

markers =
  api: 接口测试用例
  web: UI自动化测试用例
  ut: 标记单元测试用例（Unit Test）
  login: 登录相关
  pay: 支付相关
  ddt: 数据驱动测试
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

#log_file = ./logs/pytest.log
#log_file_level = info
#log_file_foemat = %(levelname)-8s %(asctime)s [%(name)s:%(lineno)s] : %(message)s
#log_file_date_format = %Y-%m-%d %H:%M:%S


;记录用例执行结果
result_log_enable = 1
;记录用例分割线
result_log_separator = 1
;分割线等级
result_log_level_separator = warning
;异常信息等级
result_log_level_verbose = info
